apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mqmohu4i9-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mqmohu4i9-java-springboot-gitops